spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
            #- Header= token, 12345
            #- Method= GET, POST
            #- Query=color, green
            # - Cookie=color, blue
          filters:
            - StripPrefix=2
            - name: SampleCookie
              args:
                message: Mensaje de prueba para productos
                name: user
                value: Carlos
        - id: Items
          uri: lb://Items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123asdg
            - AddResponseHeader=token-response, 123123
            - AddRequestParameter=name, asdfq
            - SetResponseHeader=Content-Type, text/plain