spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - name: SampleCookie
              args:
                message: Mensaje de prueba para productos
                name: user
                value: Carlos
        - id: Items
          uri: lb://Items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2